alert_types:
  fourteen_day_appointment:
    id: 1
    object_type: appointment
    categories: [urgent]
  ten_day_appointment:
    id: 2
    object_type: appointment
  last_chance_appointment:
    id: 3
    object_type: appointment
  failure_to_confirm_cancellation:
    id: 4
    object_type: appointment
  office_canceled_appointment:
    id: 6
    object_type: appointment
  office_confirmed_appointment:
    id: 8
    object_type: appointment
    categories: [urgent]
  appointment_reserved_pending:
    id: 9
    object_type: appointment
  appointment_reserved_imported:
    id: 21
    object_type: appointment
  appointment_available:
    id: 10
    object_type: appointment
    categories: [premium]
  # more appointment alerts
  rep_appointment_confirmed:
    id: 31
    object_type: appointment
    categories: [office]
  appointment_tomorrow:
    id: 32
    object_type: appointment
    categories: [office]
  request_favorite:
    id: 42
    categories: [office]
  rep_appointment_booked:
    id: 44
    object_type: appointment
    categories: [office, optional]
  rep_canceled_confirmed_appointment:
    id: 30
    object_type: appointment
    categories: [office]
  rep_canceled_booked_appointment:
    id: 45
    object_type: appointment
    categories: [office]

  # user_teammate alerts
  team_invite_received:
    id: 11
    object_type: user_teammate
  team_invite_accepted:
    id: 12
    object_type: user_teammate

  # appointment_transfer alerts
  rep_transfer_received:
    id: 14
    object_type: appointment_transfer
  rep_transfer_declined:
    id: 16
    object_type: appointment_transfer
    notification_requirements: [premium]
  rep_transfer_accepted:
    id: 17
    object_type: appointment_transfer
    notification_requirements: [premium]
  appointment_transfered_by_admin:
    id: 22

  sample_request:
    id: 18

  new_office:
    id: 19

  new_office_referral:
    id: 40
  new_office_to_office_referral:
    id: 41

  new_month:
    id: 20
    notification_requirements: [premium]
  sunshine_rep_data_request:
    id: 43
